// <auto-generated />
namespace WebAPI_for_Anugular_Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addFirstNameLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFirstNameLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131025285_addFirstNameLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
